get:
  tags:
    - data
  summary: Get the available routes
  description: Routes that are available
  responses:
    '200':
      description: successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/timestamp'
    '400':
      description: Invalid request
      content: {}
