theme:
  colors:
    primary:
      main: '#99AAB5'
    text:
      primary: '#fff'
      secondary: '#99AAB5'
    border:
      dark: '#ffffff'
      light: '#fff'
  menu:
    backgroundColor: '#263238'
    textColor: '#99AAB5'
  typography:
    links:
      color: '#fff'
    headings:
      color: '#fff'
  rightPanel:
    backgroundColor: '#23272A'
  codeSample:
    backgroundColor: '#2C2F33'


hideDownloadButton: false
